### ISSUE TITLE
No service account after creating new Datastax account

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-petclinic-reactive#7]
I've just created a new Datastax account. 
The `Service Account` was empty. I had to click on the `Add Service Account` button to create a new one.
I think we have to update the `readme.md`
![image](https://user-images.githubusercontent.com/838318/95660988-dfbae980-0b2b-11eb-8083-d235672b8916.png)

**Comment by clun** [comment]
True. This behaviour is new, let me update the READ accordlingly
